### ISSUE TITLE
Stringable is deprecated

### ISSUE THREAD

**Issue by valpackett** [agrafix/ignore#1]
Hi!

The [stringable](https://www.stackage.org/package/stringable) package has been deprecated.
[pcre-heavy](https://www.stackage.org/package/pcre-heavy) `1.0.0` uses [string-conversions](https://www.stackage.org/package/string-conversions) instead.

**Comment by agrafix** [comment]
Thanks for the notice! I do not think there's any action required for the ignore package though.
