### ISSUE TITLE
Replace pcre with tdfa

### ISSUE THREAD

**Issue by TomMD** [agrafix/ignore#2]
Related to commercialhaskell/stack#1123

Consider removing PCRE, and thus the dependency on a C library, in favor of TDFA in order to simplify the installation of tooling that is quickly becoming the foundation.

**Comment by borsboom** [comment]
The trouble here is that TDFA's Posix-compatible regexes aren't the same as the Perl-style regexes that parsing Mercurial's .hgignore requires.  It says so right in the README:

> The package does not provide Perl style regular expressions. Please look at the regex-pcre and pcre-light packages instead.

**Comment by borsboom** [comment]
@agrafix: To piggyback on this, perhaps we can discuss the possibility of defaulting the `without-pcre` flag to True?  Plenty of people are hitting trouble with libpcre when they use `cabal install stack` to build Stack, and it'd be nice if doing the build that way didn't require any extra system libraries.

**Comment by borsboom** [comment]
(just created new related issue: Don't require libpcre by default #3)
