### ISSUE TITLE
Don't require libpcre by default

### ISSUE THREAD

**Issue by borsboom** [agrafix/ignore#3]
Related to #2, can we discuss the possibility of defaulting the without-pcre flag to True? Plenty of people are hitting trouble with libpcre when they use `cabal install stack` to build Stack, and it'd be nice if doing the build that way didn't require any extra system libraries.

**Comment by agrafix** [comment]
This will probably be solved in https://github.com/commercialhaskell/stack/commit/5c2664c235e5da57dbfb7f3d7a821e00c4f1147c for stack?

**Comment by borsboom** [comment]
Indeed, that change would make this irrelevant as far as Stack is concerned.

**Comment by borsboom** [comment]
Further: I think it's more-or-less up to you at this point whether that PR gets merged.
