### ISSUE TITLE
ignore 0.1.1.0 fails to build on Mac OS X, Haskell Platform 7.10.2 fresh install 

### ISSUE THREAD

**Issue by jamescheney** [agrafix/ignore#4]
The issue is as described above.  The root cause (see below) seems to be an unmet dependency on libiconv symbols that seem to be named nonstandardly on the MacPorts version of libiconv.  Lots of MacPorts packages depend on libiconv (so arguably this is an issue with MacPorts too).  However, explicitly linking to the MacOSX official version of libiconv (instead of letting GCC find the MacPorts one) may solve the problem (http://stackoverflow.com/questions/12619600/libiconv-and-macos).

ignore 0.1.1.0 is a direct dependency of stack-0.1.6.0.

$ cabal --verbose install ignore
/usr/bin/alex --version
/usr/bin/gcc -dumpversion
/usr/bin/haddock --version
/usr/bin/happy --version
/usr/bin/hpc version
looking for tool hsc2hs near compiler in /usr/bin
found hsc2hs in /usr/bin/hsc2hs
/usr/bin/hsc2hs --version
/usr/bin/HsColour -version
/usr/bin/ghc -c /var/folders/n0/bg8ls83d23dbr2zjtdbjy5sc0000gn/T/16807282475249.c -o /var/folders/n0/bg8ls83d23dbr2zjtdbjy5sc0000gn/T/1622650073984943658.o
/usr/bin/ld -x -r /var/folders/n0/bg8ls83d23dbr2zjtdbjy5sc0000gn/T/1622650073984943658.o -o /var/folders/n0/bg8ls83d23dbr2zjtdbjy5sc0000gn/T/1144108930470211272.o
/opt/local/bin/pkg-config --version
Warning: cannot determine version of /opt/local/bin/strip :
""
/usr/bin/tar --help
Reading available packages...
Choosing modular solver.
Resolving dependencies...
Ready to install ignore-0.1.1.0
Extracting
/Users/jcheney/Library/Haskell/repo-cache/hackage.haskell.org/ignore/0.1.1.0/ignore-0.1.1.0.tar.gz
to /var/folders/n0/bg8ls83d23dbr2zjtdbjy5sc0000gn/T/cabal-tmp-34136...
Updating ignore.cabal with the latest revision from the index.
Waiting for install task to finish...
Configuring ignore-0.1.1.0...
creating
/var/folders/n0/bg8ls83d23dbr2zjtdbjy5sc0000gn/T/cabal-tmp-34136/ignore-0.1.1.0/dist/setup
creating
/var/folders/n0/bg8ls83d23dbr2zjtdbjy5sc0000gn/T/cabal-tmp-34136/ignore-0.1.1.0/dist
creating
/var/folders/n0/bg8ls83d23dbr2zjtdbjy5sc0000gn/T/cabal-tmp-34136/ignore-0.1.1.0/dist/setup
/Users/jcheney/.cabal/setup-exe-cache/setup-Simple-Cabal-1.22.4.0-x86_64-osx-ghc-7.10.2
configure --verbose=2 --ghc --prefix=/Users/jcheney/Library/Haskell
--bindir=/Users/jcheney/Library/Haskell/bin
--libdir=/Users/jcheney/Library/Haskell/ghc-7.10.2-x86_64/lib
--libsubdir=ignore-0.1.1.0 --libexecdir=/Users/jcheney/Library/Haskell/libexec
--datadir=/Users/jcheney/Library/Haskell/share
--datasubdir=ghc-7.10.2-x86_64/ignore-0.1.1.0
--docdir=/Users/jcheney/Library/Haskell/ghc-7.10.2-x86_64/lib/ignore-0.1.1.0/doc
--htmldir=/Users/jcheney/Library/Haskell/ghc-7.10.2-x86_64/lib/ignore-0.1.1.0/doc/html
--haddockdir=/Users/jcheney/Library/Haskell/ghc-7.10.2-x86_64/lib/ignore-0.1.1.0/doc/html
--sysconfdir=/Users/jcheney/Library/Haskell/etc --enable-library-profiling
--user --flags=-without-pcre
--extra-prog-path=/Users/jcheney/Library/Haskell/bin
--dependency=text=text-1.2.1.3-3718968f98d5614ccdc45c27d4e8b0a1
--dependency=pcre-heavy=pcre-heavy-1.0.0.1-d5d131b8622a8c23503b24a79377375f
--dependency=path=path-0.5.2-c5faef020da352d5ae49d27519fb6b4d
--dependency=mtl=mtl-2.2.1-7fee06b00eebbe3fa92f6d82f0fb6c19
--dependency=directory=directory-1.2.2.0-16f6a661d4e92cd8da4d681a1d197064
--dependency=base=base-4.8.1.0-075aa0db10075facc5aaa59a7991ca2f
--dependency=Glob=Glob-0.7.5-3926ffa61caaa9512bae0d6700bf5452 --disable-tests
--exact-configuration --disable-benchmarks
Redirecting build log to {handle:
/Users/jcheney/.cabal/logs/ignore-0.1.1.0.log}
Building ignore-0.1.1.0...
creating
/var/folders/n0/bg8ls83d23dbr2zjtdbjy5sc0000gn/T/cabal-tmp-34136/ignore-0.1.1.0/dist/setup
/Users/jcheney/.cabal/setup-exe-cache/setup-Simple-Cabal-1.22.4.0-x86_64-osx-ghc-7.10.2
build --verbose=2
Redirecting build log to {handle:
/Users/jcheney/.cabal/logs/ignore-0.1.1.0.log}
Failed to install ignore-0.1.1.0
Build log ( /Users/jcheney/.cabal/logs/ignore-0.1.1.0.log ):
Configuring ignore-0.1.1.0...
Flags chosen: without-pcre=False
Dependency Glob ==0.7.5: using Glob-0.7.5
Dependency base ==4.8.1.0: using base-4.8.1.0
Dependency directory ==1.2.2.0: using directory-1.2.2.0
Dependency ignore -any: using ignore-0.1.1.0
Dependency mtl ==2.2.1: using mtl-2.2.1
Dependency path ==0.5.2: using path-0.5.2
Dependency pcre-heavy ==1.0.0.1: using pcre-heavy-1.0.0.1
Dependency text ==1.2.1.3: using text-1.2.1.3
Using Cabal-1.22.4.0 compiled by ghc-7.10
Using compiler: ghc-7.10.2
Using install prefix: /Users/jcheney/Library/Haskell
Binaries installed in: /Users/jcheney/Library/Haskell/bin
Libraries installed in:
/Users/jcheney/Library/Haskell/ghc-7.10.2-x86_64/lib/ignore-0.1.1.0
Private binaries installed in: /Users/jcheney/Library/Haskell/libexec
Data files installed in:
/Users/jcheney/Library/Haskell/share/ghc-7.10.2-x86_64/ignore-0.1.1.0
Documentation installed in:
/Users/jcheney/Library/Haskell/ghc-7.10.2-x86_64/lib/ignore-0.1.1.0/doc
Configuration files installed in: /Users/jcheney/Library/Haskell/etc
Using alex version 3.1.4 found on system at: /usr/bin/alex
Using ar found on system at: /usr/bin/ar
No c2hs found
No cpphs found
Using gcc version 4.2.1 found on system at: /usr/bin/gcc
Using ghc version 7.10.2 found on system at: /usr/bin/ghc
Using ghc-pkg version 7.10.2 found on system at: /usr/bin/ghc-pkg
No ghcjs found
No ghcjs-pkg found
No greencard found
Using haddock version 2.16.1 found on system at: /usr/bin/haddock
Using happy version 1.19.5 found on system at: /usr/bin/happy
Using haskell-suite found on system at: haskell-suite-dummy-location
Using haskell-suite-pkg found on system at: haskell-suite-pkg-dummy-location
No hmake found
Using hpc version 0.67 found on system at: /usr/bin/hpc
Using hsc2hs version 0.67 found on system at: /usr/bin/hsc2hs
Using hscolour version 1.22 found on system at: /usr/bin/HsColour
No jhc found
Using ld found on system at: /usr/bin/ld
No lhc found
No lhc-pkg found
Using pkg-config version 0.28 found on system at: /opt/local/bin/pkg-config
Using strip found on system at: /opt/local/bin/strip
Using tar found on system at: /usr/bin/tar
No uhc found
Component build order: library, executable 'ignore'
creating dist/build
creating dist/build/autogen
Building ignore-0.1.1.0...
/usr/bin/ghc-pkg init dist/package.conf.inplace
Preprocessing library ignore-0.1.1.0...
Building library...
creating dist/build
/usr/bin/ghc --make -fbuilding-cabal-package -O -static -dynamic-too -dynosuf dyn_o -dynhisuf dyn_hi -outputdir dist/build -odir dist/build -hidir dist/build -stubdir dist/build -i -idist/build -isrc -idist/build/autogen -Idist/build/autogen -Idist/build -optP-include -optPdist/build/autogen/cabal_macros.h -this-package-key ignor_3CyLq1kkuOGHT2a8RY1GIo -hide-all-packages -package-db dist/package.conf.inplace -package-id Glob-0.7.5-3926ffa61caaa9512bae0d6700bf5452 -package-id base-4.8.1.0-075aa0db10075facc5aaa59a7991ca2f -package-id directory-1.2.2.0-16f6a661d4e92cd8da4d681a1d197064 -package-id mtl-2.2.1-7fee06b00eebbe3fa92f6d82f0fb6c19 -package-id path-0.5.2-c5faef020da352d5ae49d27519fb6b4d -package-id pcre-heavy-1.0.0.1-d5d131b8622a8c23503b24a79377375f -package-id text-1.2.1.3-3718968f98d5614ccdc45c27d4e8b0a1 -XHaskell2010 Ignore Ignore.Types Ignore.Core Ignore.Builder Ignore.VCS.Git Ignore.VCS.Mercurial Ignore.VCS.Darcs
[1 of 7] Compiling Ignore.Types     ( src/Ignore/Types.hs, dist/build/Ignore/Types.o )
[2 of 7] Compiling Ignore.Builder   ( src/Ignore/Builder.hs, dist/build/Ignore/Builder.o )
[3 of 7] Compiling Ignore.VCS.Git   ( src/Ignore/VCS/Git.hs, dist/build/Ignore/VCS/Git.o )
[4 of 7] Compiling Ignore.VCS.Mercurial ( src/Ignore/VCS/Mercurial.hs, dist/build/Ignore/VCS/Mercurial.o )
[5 of 7] Compiling Ignore.VCS.Darcs ( src/Ignore/VCS/Darcs.hs, dist/build/Ignore/VCS/Darcs.o )
[6 of 7] Compiling Ignore.Core      ( src/Ignore/Core.hs, dist/build/Ignore/Core.o )
[7 of 7] Compiling Ignore           ( src/Ignore.hs, dist/build/Ignore.o )
/usr/bin/ghc --make -fbuilding-cabal-package -O -prof -osuf p_o -hisuf p_hi -outputdir dist/build -odir dist/build -hidir dist/build -stubdir dist/build -i -idist/build -isrc -idist/build/autogen -Idist/build/autogen -Idist/build -optP-include -optPdist/build/autogen/cabal_macros.h -this-package-key ignor_3CyLq1kkuOGHT2a8RY1GIo -hide-all-packages -package-db dist/package.conf.inplace -package-id Glob-0.7.5-3926ffa61caaa9512bae0d6700bf5452 -package-id base-4.8.1.0-075aa0db10075facc5aaa59a7991ca2f -package-id directory-1.2.2.0-16f6a661d4e92cd8da4d681a1d197064 -package-id mtl-2.2.1-7fee06b00eebbe3fa92f6d82f0fb6c19 -package-id path-0.5.2-c5faef020da352d5ae49d27519fb6b4d -package-id pcre-heavy-1.0.0.1-d5d131b8622a8c23503b24a79377375f -package-id text-1.2.1.3-3718968f98d5614ccdc45c27d4e8b0a1 -XHaskell2010 Ignore Ignore.Types Ignore.Core Ignore.Builder Ignore.VCS.Git Ignore.VCS.Mercurial Ignore.VCS.Darcs
[1 of 7] Compiling Ignore.Types     ( src/Ignore/Types.hs, dist/build/Ignore/Types.p_o )
[2 of 7] Compiling Ignore.Builder   ( src/Ignore/Builder.hs, dist/build/Ignore/Builder.p_o )
[3 of 7] Compiling Ignore.VCS.Git   ( src/Ignore/VCS/Git.hs, dist/build/Ignore/VCS/Git.p_o )
[4 of 7] Compiling Ignore.VCS.Mercurial ( src/Ignore/VCS/Mercurial.hs, dist/build/Ignore/VCS/Mercurial.p_o )
[5 of 7] Compiling Ignore.VCS.Darcs ( src/Ignore/VCS/Darcs.hs, dist/build/Ignore/VCS/Darcs.p_o )
[6 of 7] Compiling Ignore.Core      ( src/Ignore/Core.hs, dist/build/Ignore/Core.p_o )
[7 of 7] Compiling Ignore           ( src/Ignore.hs, dist/build/Ignore.p_o )
Linking...
[(InstalledPackageId
"Glob-0.7.5-3926ffa61caaa9512bae0d6700bf5452",PackageIdentifier {pkgName =
PackageName {unPackageName = "Glob"}, pkgVersion = Version {versionBranch =
[0,7,5], versionTags = []}},ModuleRenaming True []),(InstalledPackageId
"base-4.8.1.0-075aa0db10075facc5aaa59a7991ca2f",PackageIdentifier {pkgName =
PackageName {unPackageName = "base"}, pkgVersion = Version {versionBranch =
[4,8,1,0], versionTags = []}},ModuleRenaming True []),(InstalledPackageId
"directory-1.2.2.0-16f6a661d4e92cd8da4d681a1d197064",PackageIdentifier
{pkgName = PackageName {unPackageName = "directory"}, pkgVersion = Version
{versionBranch = [1,2,2,0], versionTags = []}},ModuleRenaming True
[]),(InstalledPackageId
"mtl-2.2.1-7fee06b00eebbe3fa92f6d82f0fb6c19",PackageIdentifier {pkgName =
PackageName {unPackageName = "mtl"}, pkgVersion = Version {versionBranch =
[2,2,1], versionTags = []}},ModuleRenaming True []),(InstalledPackageId
"path-0.5.2-c5faef020da352d5ae49d27519fb6b4d",PackageIdentifier {pkgName =
PackageName {unPackageName = "path"}, pkgVersion = Version {versionBranch =
[0,5,2], versionTags = []}},ModuleRenaming True []),(InstalledPackageId
"pcre-heavy-1.0.0.1-d5d131b8622a8c23503b24a79377375f",PackageIdentifier
{pkgName = PackageName {unPackageName = "pcre-heavy"}, pkgVersion = Version
{versionBranch = [1,0,0,1], versionTags = []}},ModuleRenaming True
[]),(InstalledPackageId
"text-1.2.1.3-3718968f98d5614ccdc45c27d4e8b0a1",PackageIdentifier {pkgName =
PackageName {unPackageName = "text"}, pkgVersion = Version {versionBranch =
[1,2,1,3], versionTags = []}},ModuleRenaming True [])]
/usr/bin/ar -r -s dist/build/objs-34195/libHSignore-0.1.1.0-3CyLq1kkuOGHT2a8RY1GIo.a dist/build/Ignore.o dist/build/Ignore/Types.o dist/build/Ignore/Core.o dist/build/Ignore/Builder.o dist/build/Ignore/VCS/Git.o dist/build/Ignore/VCS/Mercurial.o dist/build/Ignore/VCS/Darcs.o
ar: creating archive dist/build/objs-34195/libHSignore-0.1.1.0-3CyLq1kkuOGHT2a8RY1GIo.a
/usr/bin/ar -r -s dist/build/objs-34195/libHSignore-0.1.1.0-3CyLq1kkuOGHT2a8RY1GIo_p.a dist/build/Ignore.p_o dist/build/Ignore/Types.p_o dist/build/Ignore/Core.p_o dist/build/Ignore/Builder.p_o dist/build/Ignore/VCS/Git.p_o dist/build/Ignore/VCS/Mercurial.p_o dist/build/Ignore/VCS/Darcs.p_o
ar: creating archive dist/build/objs-34195/libHSignore-0.1.1.0-3CyLq1kkuOGHT2a8RY1GIo_p.a
/usr/bin/ghc -shared -dynamic '-dynload deploy' -optl-Wl,-rpath,/Users/jcheney/Library/Haskell/ghc-7.10.2-x86_64/lib/Glob-0.7.5 -optl-Wl,-rpath,/Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/lib/ghc-7.10.2/array_E0sTtauuKsGDLZoT7lTbgZ -optl-Wl,-rpath,/Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/lib/ghc-7.10.2/base_GDytRqRVSUX7zckgKqJjgw -optl-Wl,-rpath,/Users/jcheney/Library/Haskell/ghc-7.10.2-x86_64/lib/base-compat-0.8.2 -optl-Wl,-rpath,/Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/lib/ghc-7.10.2/binar_IvYoLp9H6Xy3zEH13MmZwd -optl-Wl,-rpath,/Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/lib/ghc-7.10.2/rts -optl-Wl,-rpath,/Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/lib/ghc-7.10.2/bytes_6elQVSg5cWdFrvRnfxTUrH -optl-Wl,-rpath,/Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/lib/ghc-7.10.2/conta_LKCPrTJwOTOLk4OU37YmeN -optl-Wl,-rpath,/Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/lib/ghc-7.10.2/deeps_LbCWUlehDDeLxurARKDH5o -optl-Wl,-rpath,/Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/lib/ghc-7.10.2/direc_KowvXytSqazBcvN7MGpFtg -optl-Wl,-rpath,/Users/jcheney/Library/Haskell/ghc-7.10.2-x86_64/lib/dlist-0.7.1.2 -optl-Wl,-rpath,/Library/Haskell/ghc-7.10.2-x86_64/lib/exceptions-0.8.0.2 -optl-Wl,-rpath,/Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/lib/ghc-7.10.2/filep_KsGE6pHE5eZHSN90ZVax6A -optl-Wl,-rpath,/Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/lib/ghc-7.10.2/ghcpr_8TmvWUcS1U1IKHT0levwg3 -optl-Wl,-rpath,/Library/Haskell/ghc-7.10.2-x86_64/lib/hashable-1.2.3.3 -optl-Wl,-rpath,/Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/lib/ghc-7.10.2/integ_2aU3IZNMF9a7mQ0OzsZ0dS -optl-Wl,-rpath,/Library/Haskell/ghc-7.10.2-x86_64/lib/mtl-2.2.1 -optl-Wl,-rpath,/Users/jcheney/Library/Haskell/ghc-7.10.2-x86_64/lib/path-0.5.2 -optl-Wl,-rpath,/Users/jcheney/Library/Haskell/ghc-7.10.2-x86_64/lib/pcre-heavy-1.0.0.1 -optl-Wl,-rpath,/Users/jcheney/Library/Haskell/ghc-7.10.2-x86_64/lib/pcre-light-0.4.0.4 -optl-Wl,-rpath,/opt/local/lib -optl-Wl,-rpath,/Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/lib/ghc-7.10.2/prett_7UQTOB05U7lIYPkFOVraeR -optl-Wl,-rpath,/Users/jcheney/Library/Haskell/ghc-7.10.2-x86_64/lib/semigroups-0.18 -optl-Wl,-rpath,/Library/Haskell/ghc-7.10.2-x86_64/lib/stm-2.4.4 -optl-Wl,-rpath,/Users/jcheney/Library/Haskell/ghc-7.10.2-x86_64/lib/string-conversions-0.4 -optl-Wl,-rpath,/Users/jcheney/Library/Haskell/ghc-7.10.2-x86_64/lib/tagged-0.8.2 -optl-Wl,-rpath,/Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/lib/ghc-7.10.2/templ_1ejK907jvoTHoZ6iZtHeyN -optl-Wl,-rpath,/Library/Haskell/ghc-7.10.2-x86_64/lib/text-1.2.1.3 -optl-Wl,-rpath,/Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/lib/ghc-7.10.2/time_AXTdBF9VRQoBOqJT6qtmVH -optl-Wl,-rpath,/Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/lib/ghc-7.10.2/trans_3eG64VdP2vzGjP6wJiCp5X -optl-Wl,-rpath,/Library/Haskell/ghc-7.10.2-x86_64/lib/transformers-compat-0.4.0.4 -optl-Wl,-rpath,/Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/lib/ghc-7.10.2/unix_A3WgcI5QiHK4PDo4jSYdwQ -optl-Wl,-rpath,/Library/Haskell/ghc-7.10.2-x86_64/lib/unordered-containers-0.2.5.1 -optl-Wl,-rpath,/Users/jcheney/Library/Haskell/ghc-7.10.2-x86_64/lib/utf8-string-1.0.1.1 -this-package-key ignor_3CyLq1kkuOGHT2a8RY1GIo -no-auto-link-packages -package-db dist/package.conf.inplace -package-id Glob-0.7.5-3926ffa61caaa9512bae0d6700bf5452 -package-id base-4.8.1.0-075aa0db10075facc5aaa59a7991ca2f -package-id directory-1.2.2.0-16f6a661d4e92cd8da4d681a1d197064 -package-id mtl-2.2.1-7fee06b00eebbe3fa92f6d82f0fb6c19 -package-id path-0.5.2-c5faef020da352d5ae49d27519fb6b4d -package-id pcre-heavy-1.0.0.1-d5d131b8622a8c23503b24a79377375f -package-id text-1.2.1.3-3718968f98d5614ccdc45c27d4e8b0a1 dist/build/Ignore.dyn_o dist/build/Ignore/Types.dyn_o dist/build/Ignore/Core.dyn_o dist/build/Ignore/Builder.dyn_o dist/build/Ignore/VCS/Git.dyn_o dist/build/Ignore/VCS/Mercurial.dyn_o dist/build/Ignore/VCS/Darcs.dyn_o -o dist/build/libHSignore-0.1.1.0-3CyLq1kkuOGHT2a8RY1GIo-ghc7.10.2.dylib
In-place registering ignore-0.1.1.0...
/usr/bin/ghc-pkg update - --global --user '--package-db=dist/package.conf.inplace'
Preprocessing executable 'ignore' for ignore-0.1.1.0...
Building executable ignore...
creating dist/build/ignore
creating dist/build/ignore/ignore-tmp
/usr/bin/ghc --make -no-link -fbuilding-cabal-package -O -static -outputdir dist/build/ignore/ignore-tmp -odir dist/build/ignore/ignore-tmp -hidir dist/build/ignore/ignore-tmp -stubdir dist/build/ignore/ignore-tmp -i -idist/build/ignore/ignore-tmp -iapp -idist/build/autogen -Idist/build/autogen -Idist/build/ignore/ignore-tmp -optP-include -optPdist/build/autogen/cabal_macros.h -hide-all-packages -package-db dist/package.conf.inplace -package-id base-4.8.1.0-075aa0db10075facc5aaa59a7991ca2f -package-id directory-1.2.2.0-16f6a661d4e92cd8da4d681a1d197064 -package-id ignore-0.1.1.0-inplace -package-id path-0.5.2-c5faef020da352d5ae49d27519fb6b4d -XHaskell2010 app/Main.hs -threaded -rtsopts '-with-rtsopts=-N'
[1 of 1] Compiling Main             ( app/Main.hs, dist/build/ignore/ignore-tmp/Main.o )
Linking...
/usr/bin/ghc --make -fbuilding-cabal-package -O -static -outputdir dist/build/ignore/ignore-tmp -odir dist/build/ignore/ignore-tmp -hidir dist/build/ignore/ignore-tmp -stubdir dist/build/ignore/ignore-tmp -i -idist/build/ignore/ignore-tmp -iapp -idist/build/autogen -Idist/build/autogen -Idist/build/ignore/ignore-tmp -optP-include -optPdist/build/autogen/cabal_macros.h '-dynload deploy' -optl-Wl,-rpath,/Users/jcheney/Library/Haskell/ghc-7.10.2-x86_64/lib/ignore-0.1.1.0 -optl-Wl,-rpath,/Users/jcheney/Library/Haskell/ghc-7.10.2-x86_64/lib/Glob-0.7.5 -optl-Wl,-rpath,/Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/lib/ghc-7.10.2/array_E0sTtauuKsGDLZoT7lTbgZ -optl-Wl,-rpath,/Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/lib/ghc-7.10.2/base_GDytRqRVSUX7zckgKqJjgw -optl-Wl,-rpath,/Users/jcheney/Library/Haskell/ghc-7.10.2-x86_64/lib/base-compat-0.8.2 -optl-Wl,-rpath,/Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/lib/ghc-7.10.2/binar_IvYoLp9H6Xy3zEH13MmZwd -optl-Wl,-rpath,/Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/lib/ghc-7.10.2/rts -optl-Wl,-rpath,/Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/lib/ghc-7.10.2/bytes_6elQVSg5cWdFrvRnfxTUrH -optl-Wl,-rpath,/Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/lib/ghc-7.10.2/conta_LKCPrTJwOTOLk4OU37YmeN -optl-Wl,-rpath,/Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/lib/ghc-7.10.2/deeps_LbCWUlehDDeLxurARKDH5o -optl-Wl,-rpath,/Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/lib/ghc-7.10.2/direc_KowvXytSqazBcvN7MGpFtg -optl-Wl,-rpath,/Users/jcheney/Library/Haskell/ghc-7.10.2-x86_64/lib/dlist-0.7.1.2 -optl-Wl,-rpath,/Library/Haskell/ghc-7.10.2-x86_64/lib/exceptions-0.8.0.2 -optl-Wl,-rpath,/Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/lib/ghc-7.10.2/filep_KsGE6pHE5eZHSN90ZVax6A -optl-Wl,-rpath,/Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/lib/ghc-7.10.2/ghcpr_8TmvWUcS1U1IKHT0levwg3 -optl-Wl,-rpath,/Library/Haskell/ghc-7.10.2-x86_64/lib/hashable-1.2.3.3 -optl-Wl,-rpath,/Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/lib/ghc-7.10.2/integ_2aU3IZNMF9a7mQ0OzsZ0dS -optl-Wl,-rpath,/Library/Haskell/ghc-7.10.2-x86_64/lib/mtl-2.2.1 -optl-Wl,-rpath,/Users/jcheney/Library/Haskell/ghc-7.10.2-x86_64/lib/path-0.5.2 -optl-Wl,-rpath,/Users/jcheney/Library/Haskell/ghc-7.10.2-x86_64/lib/pcre-heavy-1.0.0.1 -optl-Wl,-rpath,/Users/jcheney/Library/Haskell/ghc-7.10.2-x86_64/lib/pcre-light-0.4.0.4 -optl-Wl,-rpath,/opt/local/lib -optl-Wl,-rpath,/Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/lib/ghc-7.10.2/prett_7UQTOB05U7lIYPkFOVraeR -optl-Wl,-rpath,/Users/jcheney/Library/Haskell/ghc-7.10.2-x86_64/lib/semigroups-0.18 -optl-Wl,-rpath,/Library/Haskell/ghc-7.10.2-x86_64/lib/stm-2.4.4 -optl-Wl,-rpath,/Users/jcheney/Library/Haskell/ghc-7.10.2-x86_64/lib/string-conversions-0.4 -optl-Wl,-rpath,/Users/jcheney/Library/Haskell/ghc-7.10.2-x86_64/lib/tagged-0.8.2 -optl-Wl,-rpath,/Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/lib/ghc-7.10.2/templ_1ejK907jvoTHoZ6iZtHeyN -optl-Wl,-rpath,/Library/Haskell/ghc-7.10.2-x86_64/lib/text-1.2.1.3 -optl-Wl,-rpath,/Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/lib/ghc-7.10.2/time_AXTdBF9VRQoBOqJT6qtmVH -optl-Wl,-rpath,/Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/lib/ghc-7.10.2/trans_3eG64VdP2vzGjP6wJiCp5X -optl-Wl,-rpath,/Library/Haskell/ghc-7.10.2-x86_64/lib/transformers-compat-0.4.0.4 -optl-Wl,-rpath,/Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/lib/ghc-7.10.2/unix_A3WgcI5QiHK4PDo4jSYdwQ -optl-Wl,-rpath,/Library/Haskell/ghc-7.10.2-x86_64/lib/unordered-containers-0.2.5.1 -optl-Wl,-rpath,/Users/jcheney/Library/Haskell/ghc-7.10.2-x86_64/lib/utf8-string-1.0.1.1 -hide-all-packages -package-db dist/package.conf.inplace -package-id base-4.8.1.0-075aa0db10075facc5aaa59a7991ca2f -package-id directory-1.2.2.0-16f6a661d4e92cd8da4d681a1d197064 -package-id ignore-0.1.1.0-inplace -package-id path-0.5.2-c5faef020da352d5ae49d27519fb6b4d -XHaskell2010 app/Main.hs -o dist/build/ignore/ignore -threaded -rtsopts '-with-rtsopts=-N'
Linking dist/build/ignore/ignore ...
Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      _hs_iconv in libHSbase-4.8.1.0-GDytRqRVSUX7zckgKqJjgw.a(iconv.o)
     (maybe you meant: _base_GHCziIOziEncodingziIconv_iconvEncoding9_info, _base_GHCziIOziEncodingziIconv_iconvEncoding10_info , _base_GHCziIOziEncodingziIconv_iconvEncoding10_closure , _base_GHCziIOziEncodingziIconv_iconvEncodingzuloc_closure , _hs_iconv_close , _base_GHCziIOziEncodingziIconv_iconvEncodingzuloc1_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding7_info , _base_GHCziIOziEncodingziIconv_iconvEncoding4_info , _base_GHCziIOziEncodingziIconv_iconvEncoding11_info , _base_GHCziIOziEncodingziIconv_iconvEncoding3_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding7_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding8_info , _base_GHCziIOziEncodingziIconv_iconvEncoding11_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding2_info , _base_GHCziIOziEncodingziIconv_iconvEncoding9_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding8_closure , _hs_iconv , _hs_iconv_open , _base_GHCziIOziEncodingziIconv_iconvEncoding2_closure , _base_GHCziIOziEncodingziIconv_iconvEncodingzuloc1_info , _base_GHCziIOziEncodingziIconv_iconvEncoding5_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding4_closure , _base_GHCziIOziEncodingziIconv_iconvEncodingzuloc_info )
  "_iconv_close", referenced from:
      _hs_iconv_close in libHSbase-4.8.1.0-GDytRqRVSUX7zckgKqJjgw.a(iconv.o)
     (maybe you meant: _hs_iconv_close)
  "_iconv_open", referenced from:
      _hs_iconv_open in libHSbase-4.8.1.0-GDytRqRVSUX7zckgKqJjgw.a(iconv.o)
     (maybe you meant: _hs_iconv_open)
  "_locale_charset", referenced from:
      _localeEncoding in libHSbase-4.8.1.0-GDytRqRVSUX7zckgKqJjgw.a(PrelIOUtils.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
World file is already up to date.
cabal: Error: some packages failed to install:
ignore-0.1.1.0 failed during the building phase. The exception was:
ExitFailure 1

**Comment by agrafix** [comment]
As you already mentioned, this is probably due to a missing/non-discoverable libiconv installation. The only fix would be to explicitly show cabal the correct include/lib dirs. The next stack release will not depend on ignore anymore.

**Comment by jamescheney** [comment]
Thanks.  I realize this is probably more the fault of MacPorts, in any case (I might raise an issue there too, since using a nonstandard libiconv probably breaks other things).  Happy to close if you are.

**Comment by agrafix** [comment]
Alright then, let's close this
